### PR TITLE
Options

### PR DESCRIPTION
**Pull request by LiveChief**

### CODE REVIEW

**Comment by LiveChief** [comment]
@Leopere Help??

**Comment by Leopere** [comment]
Got your base figured out already by the looks of it.

**Comment by LiveChief** [comment]
@Leopere these errors are completely fucking bullshit.

can u try and help and push new code plz??

i wanna complete this entire script today.

**Comment by Leopere** [comment]
doing `read -rp` seems extra.  the `-r` only apparently ignores the `\` escape char.

**Comment by Leopere** [comment]
I also don't have the desktop client installed let me have a go at dl'ing it.

**Comment by LiveChief** [comment]
@Leopere 

https://www.wireguard.com/install/

Windows client just came out its pretty nice, its way better than tunsafe and smaller code base.
But its still on beta and works better than tunsafe cause wireguard got their own tun device on it.

**Comment by Leopere** [comment]
We should probably chat about that kinda stuff in Discord.

**Comment by LiveChief** [comment]
IMG_20190608_192224

on a chromebook.

@Leopere 

give me 10 mins i am charging my phone right now so i can get on that my dood.

**Pull request merged**
