### PR TITLE
UNBOUND DNS OVER TLS

### PR DESCRIPTION
**Pull request by LiveChief**

### CODE REVIEW

**Comment by Leopere** [comment]
I wonder how many from that list actually support DoH I imagine it's likely only Cloudflare and maybe Google I doubt the Russians over at AdGuard DNS have upgraded yet etc...

**Comment by LiveChief** [comment]
AdGuard supports DNS OVER TLS  and DOH
AdGuard is pretty nice btw, i use it on my home network and ads are blocked on my roku and other stuff.

Mecrosoft now.

**Comment by Leopere** [comment]
https://github.com/curl/curl/wiki/DNS-over-HTTPS this may lead to what providers are supporting it currently.

**Comment by Leopere** [comment]
I like AdGuard personally as well, I also like PiHole but that seems out of scope for this.

**Comment by LiveChief** [comment]
PiHole wold work better

**Comment by Leopere** [comment]
I run mine via Docker generally because then it can hook into my Traefik reverse proxy front end with the TLS auto renewals with LetsEncrypt.  If you want to go that far you're welcomed to.  Might be a bit extra maintenance but it would be a great value add.

**Comment by Leopere** [comment]
I created an issue under #53 however at the point of adding PiHole it might make sense to just simply create a meta-installer on top of the two technologies and marry them that way in the future.  This way you can have that meta-installer be more generic than `wireguard-install`

**Pull request closed without merging**
