### PR TITLE
Enable IPV6

### PR DESCRIPTION
**Pull request by LiveChief**

### CODE REVIEW

**Comment by aaronstuder** [comment]
I just work on this for about 2 hours. I am getting somewhere but is there any benefit to IPv6?

**Comment by LiveChief** [comment]
https://www.networkcomputing.com/networking/six-benefits-ipv6

**Comment by LiveChief** [comment]
Update: The script u made isnt working.

**Comment by aaronstuder** [comment]
That's correct. Need to figure out how to setup IPv6 addresses on the server and client.

**Comment by LiveChief** [comment]
Yes , but more testing is required

**Pull request closed without merging**
