### PR TITLE
Detect of IPV6

### PR DESCRIPTION
**Pull request by Dedi-Data**
True detect of IPV6

### CODE REVIEW

**Comment by LiveChief** [comment]
```
UBUNTU:
root@ip-:/home/ubuntu/environment# bash wireguard-server.sh 
System public IPV4 address is 0. Is that correct? [y/n]: y

```

**Comment by Dedi-Data** [comment]
This is good for IPV4:
`$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)`

I am finding a better solution for IPV6

**Comment by Dedi-Data** [comment]
@LiveChief 
What about this on Ubuntu? I am checking on CentOS:
`ip -6 addr | grep inet6 |  awk '{ print $2}' | cut -d "/" -f1 | grep -v ^::1 | grep -v ^fe80`

**Comment by LiveChief** [comment]
@Dedi-Data 
can u check if the updated one works on cent os??

checked it on debian and works fine.

**Comment by LiveChief** [comment]
merged.

**Comment by Dedi-Data** [comment]
@LiveChief 
What about:
SERVER_HOST_V6=`ip -6 addr | grep inet6 | awk '{ print $2}' | cut -d "/" -f1 | grep -v ^::1 | grep -v ^fe80 `

What we should do if there isn't any IPV6 ?

**Comment by LiveChief** [comment]
if there isnt any ipv6 they cant connect via ipv6 or use ipv6

**Comment by LiveChief** [comment]
the script works fine now.

**Comment by Dedi-Data** [comment]
@LiveChief 
Please check this again: https://github.com/LiveChief/wireguard-install/pull/74#issuecomment-509032906

> if there isnt any ipv6 they cant connect via ipv6 or use ipv6
so in this case all firewalld rules will be wrong and finally it won't work

**Comment by LiveChief** [comment]
so u want it if they have IPV6 we enable ipv6 rules and if they dont have ipv6 we dont enable ipv6??

**Comment by LiveChief** [comment]
couple of days and ill have it ready.

**Comment by Dedi-Data** [comment]
@LiveChief 
Detecting of IPV6 based on my mentioned line https://github.com/LiveChief/wireguard-install/pull/74#issuecomment-509032906 is ok,
But it tries to detect an IPV6 if it exists, but we should take care for the time it doesn't exist
And in this case, we should not apply IPV6 rules

Another:
I see some problems with firewalld in the script:
assume the user has firewalld before installing this script and he has defined rules for that, the script tries to install firewalld, So it is installed before running, but if he wants to uninstall this script,  it will uninstall firewalld too !!!!

**Comment by LiveChief** [comment]
@Dedi-Data 

Give me a day or two and ill rewrite the whole script properly.

**Comment by Dedi-Data** [comment]
@LiveChief 
I recommend to don't install firewalld,
Just check for existing of that and use that, if there isn't any firewalld, use iptables rather than firewalld, even on CentOS

And I think adding forward rules on server config file is better than running them:
sample:

```
[Interface]
Address = 10.66.66.1/24,fd42:42:42::1/64
PostUp = iptables -t nat -A POSTROUTING -o ens3 -j MASQUERADE; ip6tables -t nat -A POSTROUTING -o ens3 -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -o ens3 -j MASQUERADE; ip6tables -t nat -D POSTROUTING -o ens3 -j MASQUERADE
ListenPort = 53
PrivateKey = <server private key>

[Peer]
PublicKey = <client 1 public key>
AllowedIPs = 10.66.66.2/32, fd42:42:42::2/128

[Peer]
PublicKey = <client 2 public key>
AllowedIPs = 10.66.66.3/32, fd42:42:42::3/128
```

**Pull request merged**
